### PR TITLE
Updated the project to .Net Standard 2.0 - Version 2

### PR DESCRIPTION
**Pull request by fushinoryuu**
This is the same work as in #3, but this time I made sure to not delete the git history on the files.

Let me know if you have any other questions.

### CODE REVIEW

**Comment by Brondahl** [comment]
Great; All looks fine. :)

It seems like the refactoring of the Unit Tests into distinct classes/files isn't present? I'm not fussed about this either way - it was perfectly good refactoring, but also not essential. Just checking that you've noticed.

Final thing: Testing - I'm taking it as read that the all the Unit Tests still pass, but I'd like to ensure that the nuget process still works and does successfully support all the runtimes that it's previously supported.

I'm happy to do that testing myself, but if you've already done that, I don't see any need to repeat the testing. If you *have* already done it, could you describe in detail what process you've used for testing it? (So that I can decide whether I think there are any extra edge cases that I want to cover off.)

**Comment by fushinoryuu** [comment]
I forgot about the unit tests, I have fixed that now.

I also took the liberty to delete the obsolete method and updated the read me.

I did run all the unit tests, and they are passing, but I have not done any other testing beyond that. If you wouldn't mind doing that part, it would be great!

Thanks!

**Comment by Brondahl** [comment]
Heya,

Thanks for taking out the obsolete method - I considered suggesting it, and then figured that I should probably do it myself separately, if I cared about it :)

I've done the testing and it all checks out. 👍 
I'll do a bit of git faffing to commit the stuff I added for that testing, and then release it. Probably doing that this evening (UK time).

Did you have an answer about whether you care about the credit for the work, or whether you just care about it getting in and updated?

**Comment by fushinoryuu** [comment]
Thanks for doing the extra testing.

It would be nice to keep some of the credit, since this is my first contribution to an open source project.

But if its easier for you to do it some other way, its fine.

**Comment by Brondahl** [comment]
All done :)

Incidentally, VS allows you to configure it to auto-pack the pkg, so that you don't need the CLI steps.

**Comment by fushinoryuu** [comment]
Awesome! Just saw that the new package is up on Nuget, thanks for taking my pull request.

**Pull request merged**
