### PR TITLE
Updated the project to .Net Standard 2.0

### PR DESCRIPTION
**Pull request by fushinoryuu**
I did a few different things in this pull request:

- This pull request is targeted at updating the project to run on .Net Standard 2.0.
- This is mainly so any project using any of the new .Net features can use this library.
- I deleted the duplicate projects since we are able to multi-target with the new format and still output dlls that can work on all the old versions.
- Updated the readme with instruction on how to generate new packages with the new format.
- I also moved the unit tests around to make them easier to read.

### CODE REVIEW

**Comment by Brondahl** [comment]
Overall, this looks fine. From what I can deduce from the changes, the .NET Standard integration with nuget and multi-framework targetting is WAY nicer that what I had :)

I'm concerned about the nature of some of the commits dropping git history & changes, and I'd like some clarification on the changes to the Test Framework support.

Lastly if you could confirm whether VS 2017 is a necessary requirement or not, that would be good.

**Comment by Brondahl** [comment]
#end

**Comment by Brondahl** [comment]
@fushinoryuu did you get notifications for the messages above? ... it occurs to me that I didn't @ you, so you might not have noticed them.
I don't intend to accept the Pull Request as it currently stands - I'd like to hear answers to the questions above, and to see some minor tweaks to the commit history as detailed above (unless there are good reasons that I've not understood fo the commit sequence)

**Comment by fushinoryuu** [comment]
@Brondahl I did get the notifications, but I was a bit busy this weekend. I'll answer your questions tomorrow if that's ok. Thanks!

**Comment by Brondahl** [comment]
That's fine!

I just wasn't sure - I've done basically no OpenSource collaboration, and we use internal review tools, and within-repository branches & merges at work. So I wasn't 100% clear on how PullRequests and comments work.

All the best.

**Comment by fushinoryuu** [comment]
Ok, I will try to address your question, let me know if I missed something:

- 36b2a48 The the nuspec file is not needed anymore, I guess I forgot to delete it. I will go back and do this.

- 758bc23 I updated the gitignore file using this template: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

- 261346b I am like 90% sure you need VS 2017 to work on .Net Standard and .Net Core stuff. You can always use the Community version of VS which is completely free and lets you do everything you need.

- Also 261346b I have never squashed commits, but I can look into doing this.

- f93c980 In the past when I have tried to just update the target framework, it causes issues since the .csproj file is not always the same between versions. If you want I can go back and update the target framework.

Let me know if I missed anything.

**Comment by Brondahl** [comment]
Cool. Responses...

    36b2a48  Cool, that's fine then. Will that be a 2nd PR, or will it get added to this PR?
    758bc23 That makes sense - no issues with that.
    261346b Ah, I suspected that might be the case. Thanks for the point about Community Edition - I hadn't considered that. Should be fine then.
    261346b I'm very comfortable with manipulating commits, I'm happy to do this, if there's no other reason for them to be separate.
    f93c980 Really? I've never had issues with that - VS has always updated the format where necessary, for me. :shrug:  If we do the squashing, then we'll be able to tell whether there are any other changes.


So my remaining question is about the GitHub workflow ... If I "Merge Pull Request" is that going to merge it directly onto master of my repository, or will it merge it in as a branch, which I can then modify before I put it into master and push it?

I can see how to manually pull your fork in as a branch, but I'm not clear on whether that loses you the credit for the work? Do you *care* about the credit for the work? (I'm *very* happy to credit you, but if you don't care about that, then we shouldn't tie ourselves in knots to achieve it?)

I assume this is prompted by 24PullRequests? Do that count the PR as soon as it's raised, or only if it's merged in?

**Comment by fushinoryuu** [comment]
I'll just take care of it, no worries. I'll close this pull request for now and I'll open a new one in a bit.

**Pull request closed without merging**
